---
- name: Instalar servidor web y p치gina web est치tica
  hosts: all
  become: yes

  tasks:
    - name: Asegurar que nginx se encuentre actualizado
      apt:
        name: nginx
        state: latest

    - name: Actualizar p치gina web est치tica
      template:
        src: index.j2
        dest: /var/www/html/index.html
